#ifndef __STM32F10X_H__
#define __STM32F10X_H__


//Õ‚…Ëµÿ÷∑
#define PERIPHERALS_BASE_ADDRESS	0x40000000
#define APB1_BASE_ADDRESS		    PERIPHERALS_BASE_ADDRESS
#define APB2_BASE_ADDRESS 		    (PERIPHERALS_BASE_ADDRESS+0x10000)
#define AHB_BASE_ADDRESS		    (PERIPHERALS_BASE_ADDRESS+0x20000)

//RCC
#define RCC_BASE_ADDRESS             (AHB_BASE_ADDRESS+0x1000)

#endif
