#define uint32_t		unsigned int

//Õ‚…Ëµÿ÷∑
#define PERIPHERALS_BASE_ADDRESS	0x40000000
#define APB1_BASE_ADDRESS		    PERIPHERALS_BASE_ADDRESS
#define APB2_BASE_ADDRESS 		    (PERIPHERALS_BASE_ADDRESS+0x10000)
#define AHB_BASE_ADDRESS		    (PERIPHERALS_BASE_ADDRESS+0x20000)

//GPIO
#define GPIOA_BASE_ADDRESS			(APB2_BASE_ADDRESS+0x0800)
#define GPIOB_BASE_ADDRESS			(APB2_BASE_ADDRESS+0x0C00)
#define GPIOC_BASE_ADDRESS			(APB2_BASE_ADDRESS+0x1000)
#define GPIOD_BASE_ADDRESS			(APB2_BASE_ADDRESS+0x1400)
#define GPIOE_BASE_ADDRESS			(APB2_BASE_ADDRESS+0x1800)
#define GPIOF_BASE_ADDRESS			(APB2_BASE_ADDRESS+0x1C00)
#define GPIOG_BASE_ADDRESS			(APB2_BASE_ADDRESS+0x2000)

//RCC
#define RCC_BASE_ADDRESS             (AHB_BASE_ADDRESS+0x1000)
